# Generated by Django 5.1.6 on 2025-02-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Tel',
        ),
    ]
